### ISSUE TITLE
Outputs "Unsupported system ()" on One Notebook K33-4E

### ISSUE THREAD

**Issue by phiresky** [Unrud/init-headphone#1]
I have [this notebook](http://www.one.de/shop/product_info.php?products_id=10194) which uses the Clevo W230SS barebone.

The script returns "Unsupported system ()".  `dmidecode -s system-product-name` returns an empty string.

When adding `""` to `SUPPORTED_SYSTEM_PRODUCT_NAMES`, it correctly reenables the headphone jack.

Any other ways to identify the system without dmidecode?

**Comment by Unrud** [comment]
Hi,
what does `dmidecode -s baseboard-product-name` return?

**Comment by phiresky** [comment]
Yes, that outputs `W230SS`.

**Comment by Unrud** [comment]
Fixed: d23ae1642bd3593ae26d7170918366225414f7fb

**Comment by phiresky** [comment]
Thanks!
