### ISSUE TITLE
Add documentation for Systemd-suspend hook

### ISSUE THREAD

**Issue by roncapat** [Unrud/init-headphone#14]
I suggest to add at least to the README instructions to schedule automatic headphones reinitialization after resuming from suspension state. I can provide the README and the trivial configuration file needed to automatically execute init-headphone on resume. Just tell me if it would be helpful and I'll contribute with a PR. From a packaging perspective, a new file has to be deployed, and I'm actually found only on Ubuntu, but basically systemd-supend uses one of two possible paths so it wouldn't be too difficult to address all distros in principle. 

PS: my machine is a Clevo W230SD.

**Comment by Unrud** [comment]
The build system detects systemd [[1](https://github.com/Unrud/init-headphone/blob/master/configure.ac#L4), [2](https://github.com/Unrud/init-headphone/blob/aa247b6d008dcddfa0624c0a1bd944b9ea14e75d/Makefile.am#L4)] and installs the service file automatically [[3](https://github.com/Unrud/init-headphone/blob/master/init-headphone.service.in)].

**Comment by roncapat** [comment]
Oh ok sorry for not having checked, it wasn't the case on my system, I had to do it manually. Maybe I'll try to investigate the cause.

**Comment by Unrud** [comment]
Run ``./configure --with-systemdsystemunitdir=yes``.
It will show an error if it's unable to find systemd instead of silently ignoring it.
