### ISSUE TITLE
error when run "sudo init-headphone"

### ISSUE THREAD

**Issue by namirinz** [Unrud/init-headphone#15]
got error message :

ERROR:Can't transfer data on I2C bus
ERROR:Operation failed

**Comment by Unrud** [comment]
Run with the `--verbose` argument.

**Comment by namirinz** [comment]
I use Manjaro only (No windows dual boot)
### 
INFO:Version: 0.14
INFO:Trying to add module to the kernel: i2c_dev
INFO:Trying to add module to the kernel: i2c_i801
DEBUG:Available i2c busses: ['i915 gmbus tc1', 'Synopsys DesignWare I2C adapter', 'i915 gmbus dpb', 'i915 gmbus tc6', 'NVIDIA i2c adapter 1 at 2b:00.0', 'i915 gmbus tc4', 'AUX D/port D', 'i915 gmbus tc2', 'AUX A/port A', 'i915 gmbus dpc', 'i915 gmbus dpa', 'Synopsys DesignWare I2C adapter', 'i915 gmbus tc5', 'SMBus I801 adapter at 4040', 'i915 gmbus tc3', 'AUX C/port C']
DEBUG:Supported i2c bus names: ['SMBus I801 adapter']
DEBUG:Selected i2c bus: SMBus I801 adapter at 4040
INFO:Opening I2C bus: /dev/i2c-14
INFO:Setting I2C slave address: 115
INFO:Writing byte data on I2C bus: (device_cmd: 0xa, value: 0x41)
**ERROR:Can't transfer data on I2C bus**
INFO:Closing I2C bus
**ERROR:Operation failed**
DEBUG:Exception occurred:
Traceback (most recent call last):
  File "/usr/local/sbin/init-headphone", line 362, in <module>
    main()
  File "/usr/local/sbin/init-headphone", line 320, in main
    init()
  File "/usr/local/sbin/init-headphone", line 252, in init
    set_effect(DEFAULT_EFFECT)
  File "/usr/local/sbin/init-headphone", line 266, in set_effect
    write_data_to_device(DATA_DISABLE_OUTPUT +
  File "/usr/local/sbin/init-headphone", line 246, in write_data_to_device
    write_prolog(i2c_bus)
  File "/usr/local/sbin/init-headphone", line 237, in write_prolog
    i2c_bus.write_byte_data(0x0a, 0x41)
  File "/usr/local/sbin/init-headphone", line 147, in write_byte_data
    self.__access(I2C_SMBUS_WRITE, device_cmd, I2C_SMBUS_BYTE_DATA, data)
  File "/usr/local/sbin/init-headphone", line 139, in __access
    raise OSError(err, os.strerror(err))
OSError: [Errno -1] Unknown error -1

**Comment by Unrud** [comment]
> OSError: [Errno -1] Unknown error -1

That's not very helpful. Maybe **dmesg** shows something useful.
