### ISSUE TITLE
XMG P305 not working

### ISSUE THREAD

**Issue by THS-on** [Unrud/init-headphone#2]
Hello,
I have a XMG P305 this is a German rebrand form the w230sd and i have the same issue with my Audioport. Can you add this Notebook to the Script?
dmidecode -s baseboard-product-name output:
    # SMBIOS implementations newer than version 2.7 are not
    # fully supported by this version of dmidecode.
    XMG P305
Thanks THS

**Comment by Unrud** [comment]
Hi,
try to start the script with the `-f` argument. This skips the model check with dmidecode.

**Comment by THS-on** [comment]
Hi,
I've switched distro from Arch to Linux Mint and the only thing that i had to add to the script was under 
SUPPORTED_BASEBOARD_PRODUCT_NAMES: "XMGxP305"
Now my system works perfectly fine.

**Comment by Unrud** [comment]
Removed model check in version 0.9: 73bdad2098d9e9a0a853b865e076cd70c0f91f3a
