### ISSUE TITLE
Supported models are confusing

### ISSUE THREAD

**Issue by zhou13** [Unrud/init-headphone#5]
When I first find this package, I am confused by the "supported models" because it doesn't contain the model of my laptop p150sm-a.  I guess this probably works on all the clevo laptops (if that laptop needs to reinit its heaadphone) so maybe the supported models can be removed. (I have already seen that model check has been removed from the source code)

**Comment by Unrud** [comment]
I've updated the list of supported models in the ReadMe and added a hint, saying that it's subject to change.
Also removed the supported models from the program itself.
