### ISSUE TITLE
Gentoo repo

### ISSUE THREAD

**Issue by cono** [Unrud/init-headphone#6]
Hello,

Thanks for replying in https://bugzilla.kernel.org/show_bug.cgi?id=75151
Already utilized your fresh script for my system and it works perfectly!

Wanted to propose to make a gentoo repo for this.
Its pretty easy to make, simplest example you can find here: https://github.com/gentoo-mirror/yoreek
After that on my gentoo system I just add:

```
% cat /etc/portage/repos.conf/yoreek.conf 
[yoreek]
location = /usr/local/portage/yoreek
sync-type = git
sync-uri = https://github.com/gentoo-mirror/yoreek.git
auto-sync = true
```

More complex example: https://github.com/nE0sIghT/vortex-overlay
Really complex but full example: https://github.com/dantrell/gentoo-overlay-dantrell-gnome

Let me know your thoughts.

**Comment by Unrud** [comment]
Hi,

I'm not interested in maintaining a Gentoo repo but you're free to do so.
