### ISSUE TITLE
effect changes on -v argument

### ISSUE THREAD

**Issue by markolo25** [Unrud/init-headphone#7]
is this intended behavior or a bug?

**Comment by Unrud** [comment]
Hi,

the behaviour with and without the `-v` argument should be exactly the same (besides the increased logging level). Can you provide the complete command line, the observed and expected behaviour?

**Comment by markolo25** [comment]
mark@mark-P65-P67SE ~> sudo init-headphone effect4
mark@mark-P65-P67SE ~> echo everything here is boosted
everything here is boosted
mark@mark-P65-P67SE ~> sudo init-headphone -v
INFO:root:Version: 0.11
INFO:root:Trying to add module to the kernel: i2c_dev
INFO:root:Trying to add module to the kernel: i2c_i801
DEBUG:root:Available i2c busses: ['i915 gmbus ssc', 'i915 gmbus vga', 'i915 gmbus panel', 'i915 gmbus dpc', 'i915 gmbus dpb', 'i915 gmbus dpd', 'DPDDC-A', 'DPDDC-B', 'DPDDC-D', 'SMBus I801 adapter at f040']
DEBUG:root:Supported i2c bus names: ['SMBus I801 adapter']
DEBUG:root:Selected i2c bus: SMBus I801 adapter at f040
INFO:SMBus:Opening I2C bus: /dev/i2c-9
INFO:SMBus:Setting I2C slave address: 115
INFO:SMBus:Writing byte data on I2C bus: (device_cmd: 0xa, value: 0x41)
INFO:SMBus:Read byte data on I2C bus: (device_cmd: 0x4, value: 0x88)
INFO:SMBus:Writing byte data on I2C bus: (device_cmd: 0x4, value: 0x88)
INFO:SMBus:Read byte data on I2C bus: (device_cmd: 0x9, value: 0x22)
INFO:SMBus:Writing byte data on I2C bus: (device_cmd: 0x9, value: 0x22)
INFO:SMBus:Writing byte data on I2C bus: (device_cmd: 0x0, value: 0x86)
INFO:SMBus:Writing byte data on I2C bus: (device_cmd: 0x4, value: 0xee)
INFO:SMBus:Writing byte data on I2C bus: (device_cmd: 0x5, value: 0x3)
INFO:SMBus:Writing byte data on I2C bus: (device_cmd: 0x7, value: 0x40)
INFO:SMBus:Writing byte data on I2C bus: (device_cmd: 0x8, value: 0x84)
INFO:SMBus:Writing byte data on I2C bus: (device_cmd: 0x9, value: 0xff)
INFO:SMBus:Writing byte data on I2C bus: (device_cmd: 0x0, value: 0x82)
INFO:SMBus:Closing I2C bus
mark@mark-P65-P67SE ~> echo default effect occurs
default effect occurs
mark@mark-P65-P67SE ~>

**Comment by markolo25** [comment]
sorry, I thought -v was the version argument i didn't know there was a verbose argument so i guess this is the intended behavior
